### PR TITLE
Syntax highlighting

### PR DESCRIPTION
**Pull request by rlisahuang**
Creating this to share progress on debugging the failure of importing lisp syntax highlights

### CODE REVIEW

**Comment by rlisahuang** [comment]
The original code has prop types declared at the bottom. I can move them up.

**Comment by pelikhan** [comment]
My experience is that it is most convenient to declare them in the method signature

…(props: { code: number, … })

You rarely need s named type for those.

Also stay away from « My… » type of names. Sharing is caring.
________________________________

**Comment by pelikhan** [comment]
nit: don't reuse branches as it pollutes the commit history

**Review by pelikhan — APPROVED** [review]

**Comment by pelikhan** [comment]
This replaces https://github.com/microsoft/z3guide/pull/96 ?

**Comment by rlisahuang** [comment]
No, this is solely for syntax highlighting. Still wip because it apparently is not working... But I ran browser dev tools (in a very human-unreadable way) to figure out that `lisp` _did_ get loaded to the `Prism` object during server-side rendering, through the `prismIncludeLanguages` function provided by `docusaurus`. The question now is what happened afterwards that we lost the imported `lisp` again. 

Will need some help with debugger setup in vscode because breakpoints set in `.tsx` files won't work in the existing debugging setting (`.vscode/launch.json`) for node (`yarn build`).

**Comment by pelikhan** [comment]
(1) make sure to upgrade docusaurus to the officual release
(2) search their discussions for something similar
(3) ask for guidance at https://github.com/facebook/docusaurus/discussions

**Comment by rlisahuang** [comment]
Already on latest. This debug plugin might be helpful https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-debug

**Comment by rlisahuang** [comment]
I think I found a possible cause for the missing highlights. #98 addresses some missing CSS that the native `CodeBlock` has. Could be the reason.

**Comment by rlisahuang** [comment]
Closing this branch. Future work in #99 .

**Pull request closed without merging**
