### PR TITLE
Typecheck JS bindings

### PR DESCRIPTION
**Pull request by bakkot**
As mentioned [here](https://github.com/Z3Prover/z3/pull/6048#issuecomment-1193051202), the JS bindings give confusing errors if you don't have typechecking. This PR bundles and ships TypeScript to the client (including its built-in libraries and the types for Z3) and does typechecking there, which should make the experience of the interactive demos for the high-level bindings a lot more pleasant.

The same code also does typechecking when rendering the initial outputs server-side.

The code linked in the above comment now has a much friendlier error:

Screen Shot 2022-07-24 at 4 18 10 PM

### CODE REVIEW

**Comment by NikolajBjorner** [comment]
looks like quite a leap in fidelity.

**Comment by rlisahuang** [comment]
Thanks for the proposed changes. Typechecking would be indeed helpful.

We are aiming for separate the documentation framework from the z3-specific stuff as much as possible. Would it be possible to put the related code for typechecking JS bindings in a standalone npm package?

**Review by rlisahuang — CHANGES_REQUESTED** [review]
Thanks for the proposed changes. Typechecking would be indeed helpful.

We are aiming for separate the documentation framework from the z3-specific stuff as much as possible. Would it be possible to put the related code for typechecking JS bindings in a standalone npm package?

**Comment by bakkot** [comment]
I don't think the code for typechecking JS bindings would be would be useful for any other project, so no, I don't think it makes sense for it to be standalone npm package. It's already in its own subdirectory; that's the standard practice. I could move it to a subdirectory outside of `website` if you'd like?

**Comment by rlisahuang** [comment]
That makes sense. No need to move it outside of `website` for now. Will merge the code in a bit.

**Pull request closed without merging**
