### PR TITLE
failing the build on z3 runtime errors

### PR DESCRIPTION
**Pull request by rlisahuang**
TODOs:
- [x] do not fail if the `no-build` or `ignore-errors` flags are set
- [ ] proper logging to github actions with github annotations?

(No one is going to review the code; PRs are for communication and sanity checks for myself)

### CODE REVIEW

**Comment by NikolajBjorner** [comment]
oh, I read the code before I read "quay.io/pypa/manylinux2010_x86_64:latest" ;)

**Comment by rlisahuang** [comment]
Now supporting meta flags for ignoring z3 runtime errors in the following format:
~~~
```z3 no-build
give me the error on the webpage I know it is invalid
```
~~~
and
~~~
```z3 ignore-errors
I know this snippet is problematic but I want to teach about error messages so show them
```
~~~

More documentations to follow once this is merged into main

**Comment by NikolajBjorner** [comment]
```
- Snippet: 
Error:  Client bundle compiled with errors therefore further build is impossible.
(declare-const x Int)
(declare-const y Int)
(declare-const z Int)
(push)
(assert (= (+ x y) 10))
(assert (= (+ x (* 2 y)) 20))
(check-sat)
(pop) ; remove the two assertions
(push) 
(assert (= (+ (* 3 x) y) 10))
(assert (= (+ (* 2 x) (* 2 y)) 21))
(check-sat)
(declare-const p Bool)
(pop)
(assert p) ; error, since declaration of p was removed from the stack
- Error Msg: 
sat
unsat
(error "line 15 column 8: unknown constant p")
```

expected

```
- Hash: 
c732e84331cfb6e135c7f9ab5af430855af05f60
******************************************
Error: 
******************************************
Z3 (version 4.8.17) Runtime Error
- Snippet: 
(declare-const l1 (List Int))
(declare-const l2 (List Int))
(declare-const l3 (List Int))
(declare-const x Int)
(assert (not (= l1 nil)))
(assert (not (= l2 nil)))
(assert (= (head l1) (head l2)))
(assert (not (= l1 l2)))
(assert (= l3 (insert x l2)))
(assert (< x 100))
(check-sat)
(get-model)
(assert (= (tail l1) (tail l2)))
(check-sat)
- Error Msg: 
(error "line 1 column 20: unknown sort 'List'")
(error "line 2 column 19: unknown sort 'List'")
(error "line 3 column 19: unknown sort 'List'")
(error "line 5 column 16: unknown constant l1")
(error "line 6 column 16: unknown constant l2")
(error "line 7 column 17: unknown constant l1")
(error "line 8 column 16: unknown constant l1")
(error "line 9 column 11: unknown constant l3")
sat
(
  (define-fun x () Int
    99)
)
(error "line 13 column 17: unknown constant l1")
```

to be fixed with next release

```
sat
- Hash: 
ce8bbec151640f145992581f6af5970c2d316cf5
******************************************
    at runMicrotasks (<anonymous>)
Error: 
******************************************
Z3 (version 4.8.17) Runtime Error
- Snippet: 
(set-option :smt.mbqi true)
(declare-fun f (Int Int) Int)
(declare-const a Int)
(declare-const b Int)
(assert (forall ((x Int)) (= (f x x) (+ x a))))
(assert (< (f a b) a))
(assert (< a 0))
(check-sat)
(get-model)
(echo evaluating (f (+ a 10) 20)...)
(eval (f (+ a 10) 20))
- Error Msg: 
sat
(
  (define-fun b () Int
    0)
  (define-fun a () Int
    (- 1))
  (define-fun f ((x!0 Int) (x!1 Int)) Int
    (ite (and (= x!0 (- 1)) (= x!1 0)) (- 2)
      (+ (- 1) x!0)))
)
(error "line 13 column 6: invalid command argument, string expected")
```

Need to change echo to echo "..."


```
8
- Hash: 
fbf3b89e0e28e0886fc2e3233127dd7747[231](https://github.com/microsoft/z3guide/runs/7206700152?check_suite_focus=true#step:5:232)041
******************************************
Error: 
******************************************
Z3 (version 4.8.17) Runtime Error
- Snippet: 
(help-tactic)
- Error Msg: 
(error "line 1 column 13: parallel tactic is disabled in single threaded mode")
```

to be fixed with release

```
- Hash: 
[285](https://github.com/microsoft/z3guide/runs/7206700152?check_suite_focus=true#step:5:286)6f0e6a0d1df8445d98754831b708772c4393a
******************************************
    at runMicrotasks (<anonymous>)
Error: 
******************************************
Z3 (version 4.8.17) Runtime Error
- Snippet: 
(help-tactic)
```

to be fixed with release

```
- Error Msg: 
(error "line 1 column 13: parallel tactic is disabled in single threaded mode")
```

to be fixed with release

```
- Hash: 
2856f0e6a0d1df8445d98754831b708772c4393a
******************************************
    at runMicrotasks (<anonymous>)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by NikolajBjorner** [comment]
Can you add `ignore-errors` to the following:

```
(declare-const x Int)
(declare-const y Int)
(declare-const z Int)
(push)
(assert (= (+ x y) 10))
(assert (= (+ x (* 2 y)) 20))
(check-sat)
(pop) ; remove the two assertions
(push) 
(assert (= (+ (* 3 x) y) 10))
(assert (= (+ (* 2 x) (* 2 y)) 21))
(check-sat)
(declare-const p Bool)
(pop)
(assert p) ; error, since declaration of p was removed from the stack
- Error Msg: 
sat
unsat
```

**Comment by NikolajBjorner** [comment]
and for remaining the `no-build` based on walkthrough of errors? Then push.

**Comment by NikolajBjorner** [comment]
updated some other examples as well.

**Comment by rlisahuang** [comment]
I see that changes are addressed now. Closing the PR.

**Pull request merged**
