### PR TITLE
Custom editor

### PR DESCRIPTION
**Pull request by rlisahuang**
Done:
- CopyButton is back
- Built our native GithubDiscussionBtn and put it next to the CopyButton inside the editor (so only available when hovering over the editor)
  - Problem: positioning needs some more work with read-only editors (i.e., the Python blocks)
- Move RunButton down to be underneath the editor and keep the text consistent (so no longer "Edit and Run")

Still _very_ stuck:
- [ ] Syntax highlighting: PrismJS never picks up my call to explicitly include the highlighting for `lisp` despite the import

TODOs:
- [ ] Line numbers (maybe another huge road block)
- [ ] "Save to file" button next to CopyButton?
- [x] Make Playground always editable

### CODE REVIEW

**Comment by rlisahuang** [comment]
Screenshot: 
- CopyButton and GithubDiscussionBtn when hovering over the custom editor
- Moved RunButton down

Screen Shot 2022-08-09 at 8 14 21 AM

**Comment by rlisahuang** [comment]
Screenshot:
- Playground Editor is always editable
Screen Shot 2022-08-09 at 8 14 42 AM

**Comment by pelikhan** [comment]
can you default the playground editor to something like 20 lines? it's kind of weid as a single line.

**Comment by rlisahuang** [comment]
Yes, I also just got a complaint on the Playground Editor being too small / indicating that it would not run larger examples. Either we add more lines to the editor, or just use a larger example with more than `echo` commands.

**Comment by pelikhan** [comment]
You should be able to configure how many minimum rows on the text editor.

**Comment by pelikhan** [comment]
Can be a separate PR of course

**Comment by rlisahuang** [comment]
Moving unfinished items to separate PR. Closing and merging.

**Pull request merged**
